### ISSUE TITLE
Expose Pollution Level to HA

### ISSUE THREAD

**Issue by semyonchetvertnyh** [xumxum/ha-cyprus-weather#1]
Hello!

First of all, thank you for such useful integration. I've installed it and all entities were exposed successfully.

But is there a way to expose Pollution Level to HA as well? I mean this:
```
pollution_levels_str = {
    0:'unknown', 1:'Low',2:'Moderate',3:'High',4:'Very High'
}
```

**Comment by semyonchetvertnyh** [comment]
And maybe even `Updated on` date time from https://www.airquality.dli.mlsi.gov.cy?

**Comment by xumxum** [comment]
![image](https://github.com/xumxum/ha_cyprus_weather/assets/15927448/9e0995ad-4a3c-43f9-9432-4b467fcc7a4e)

polution_level is already exposed as an attribute of the sensor, which is a string. You can display it in HA as an entity card, select polution_level attribute

**Comment by xumxum** [comment]
![image](https://github.com/xumxum/ha_cyprus_weather/assets/15927448/9f50de8b-273e-4a3d-b1de-5bf346f82886)

Regarding updated , HA keeps track of when it was updated/changed..If you hover over the sensor, you will see last time was changed/updated..if you google it, there is a way to get this datetime from a sensor ..and display it

Glad you like and use the integration

**Comment by semyonchetvertnyh** [comment]
Oh, that's right, I found everything I need! Thank you for your help!
